### ISSUE TITLE
v0.2.8 Failed to load styles since latest npm release is v0.2.7

### ISSUE THREAD

**Issue by ziglef** [Chaoyingz/flect#10]
**Describe the bug**
When creating a new project with flect v0.2.8 either via the cookiecutter or by hand, styles are not loaded as the flect v0.2.8 package does not exist on npm

**To Reproduce**
1. Create a new flect project via cookiecutter template for example
2. rye sync
3. make dev
4. Go to `http://127.0.0.1:8000`
5. Confirm styles are missing

**Expected behavior**
Expect styles to load from flect npm package

**Screenshots**
![2024-03-26-142529_2814x1442_scrot](https://github.com/Chaoyingz/flect/assets/3718162/341d23d3-6349-4771-a353-4ef6cf4c5588)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 123.0.6312.58

**Additional context**
Workaround for now, change line 18 of `flect/render.py` to `FLECT_PREBUILT_URI = "https://unpkg.com/@chaoying/flect-prebuilt@0.2.7/dist/assets"` which is the latest version available on NPM

**Comment by Chaoyingz** [comment]
Thanks for reporting this! You're right, flect v0.2.8 hasn't been published to npm yet. I'll upload it soon. Your workaround is a good temporary solution.
